// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs_rw9hEIKH6y1-O0kpyt6Y8lExMoqWXA',
    appId: '1:110609193261:web:501ac5f82f1ae89fab1ba4',
    messagingSenderId: '110609193261',
    projectId: 'service-app-b4ff2',
    authDomain: 'service-app-b4ff2.firebaseapp.com',
    databaseURL: 'https://service-app-b4ff2-default-rtdb.firebaseio.com',
    storageBucket: 'service-app-b4ff2.appspot.com',
    measurementId: 'G-LYQM9EVCVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdwJ4RGCJGFinpc4lg3EgOY9zTwLLETWc',
    appId: '1:110609193261:android:5ef0de8bb5832155ab1ba4',
    messagingSenderId: '110609193261',
    projectId: 'service-app-b4ff2',
    databaseURL: 'https://service-app-b4ff2-default-rtdb.firebaseio.com',
    storageBucket: 'service-app-b4ff2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7G3ICxxRwo8m82VG_NRFnb3qPw9w2TzE',
    appId: '1:110609193261:ios:d6bf808315e0c54fab1ba4',
    messagingSenderId: '110609193261',
    projectId: 'service-app-b4ff2',
    databaseURL: 'https://service-app-b4ff2-default-rtdb.firebaseio.com',
    storageBucket: 'service-app-b4ff2.appspot.com',
    iosClientId: '110609193261-1qno5vafq3tpjl7te3diegujforrqsd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAntonxBoilerplate',
  );
}
